name = "GemmKernels"
uuid = "312cec97-f96c-4f55-a63d-8e567f91b59b"
authors = ["Thomas Faingnaert and contributors"]
version = "0.1.0"

[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LLVM = "929cbde3-209d-540e-8aea-75f648917ca0"
LLVMLoopInfo = "8b046642-f1f6-4319-8d3c-209ddc03c586"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CUDA = "3.5, 4, 5"
ForwardDiff = "0.10"
LLVM = "3, 4, 5, 6"
LLVMLoopInfo = "1"
julia = "1.6"
